<?php $form->setAttribute('role', 'form'); ?>
<?php echo $this->form()->openTag($form) ?>
    <?php foreach ($form as $element): ?>
        <?php $isButton = $element instanceof Zend\Form\Element\Button; ?>
        <?php $isCheckbox = $element instanceof Zend\Form\Element\Checkbox || $element->getAttribute('type') == 'checkbox'; ?>
        <?php if ($element->getLabel() != null && !$isButton && !$isCheckbox): ?>
            <?php echo $this->formLabel($element) ?>
        <?php endif ?>
        <?php if ($isButton): ?>
            <?php $element->setAttribute('class', 'btn btn-default'); ?>
            <?php echo $this->formButton($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
            <?php echo $this->formSelect($element) . $this->formElementErrors($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
             <div class="checkbox">
                <?php echo $this->formMultiCheckbox($element) . $this->formElementErrors($element) ?>
             </div>    
        <?php elseif ($isCheckbox): ?>
            <?php $element->setUseHiddenElement(false); ?>
            <div class="checkbox">
                <label><?php echo $this->formCheckbox($element) . $element->getLabel() ?></label>
            </div>
        <?php else: ?>
             <div class="form-group">
                <?php $element->setAttribute('class', 'form-control'); ?>
                <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>    
            </div>
        <?php endif ?>
<?php endforeach ?>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?php echo $this->form()->closeTag();