<?php
/*$fm = $this->flashMessenger()->setNamespace('zfcuseradmin')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}*/
?><table>
    <?php
    foreach ($this->users as $user)
    {
        print "<tr>";
        foreach($this->userlistElements as $element)
        {
            $func = 'get' . ucfirst($element);
            print "<td class='row_" . $element . "'>" . $user->$func() . "</td>";
        }
        $editLink = $this->url('zfcadmin/user/edit', array('userId' => $user->getId()));
        $deleteLink = $this->url('zfcadmin/user/remove', array('userId' => $user->getId()));
        print "<td><a href='" . $editLink . "'>Edit</a></td><td><a href='" . $deleteLink . "'>Delete</a></td></tr>";
    }
    ?>
</table>
<?php echo $this->paginationControl($this->users, 'Sliding', 'zfc-user-admin/user-admin/pagination_userlist.phtml'); ?>
